### PR TITLE
Increase forecast fetch attempts to ten

### PR DESCRIPTION
**Pull request by autoSteve**
Extends retries to ten and fixes a minor exception issue.

### CODE REVIEW

**Comment by autoSteve** [comment]
I hacked all the changes into my prod instance and am waiting to see what happens when forecast next acquires.

**Comment by autoSteve** [comment]
What are the chances? Hope it takes more than five goes... 🤣

image

**Comment by autoSteve** [comment]
It fetched eventually after five retries, showing that the 429s still get feisty at times.

If this had have been the previous code it would have been a failure to acquire, so I'm calling this. The code is written in such a way that the initial attempt counts as a "try", so six tries in all failed this time, collecting on the seventh attempt.

This is a fairly simple change to the code. Should be all good to review.

**Review by BJReplay — COMMENTED** [review]
Yeah, I think this is pointless, but the changes look OK.

**Pull request merged**
