### PR TITLE
Update Readme, remove Info, rename Licence

### PR DESCRIPTION
**Pull request by BJReplay**
Consolidate readme.md and info.me for better readme experience in HACSs.

### CODE REVIEW

**Comment by BJReplay** [comment]
Key reason for change was to remove info.md so that readme.md is the file that HACS pulls in for the component, so info.md now included (and linked) from readme.md.  Also included a couple more badges at the top of the readme.  Commented out the HACS default badge, ready to re-include hopefully any day now.

**Comment by BJReplay** [comment]
P.S. happy for any wordsmithing.

**Comment by BJReplay** [comment]
Oh, sorry, forgot to add re-ordered automation examples, and added some notes explaining them.  Splitting available API calls between sunrise and sunset with randomisation is now first example, and is recommended.

**Comment by autoSteve** [comment]
Proof reading...

**Comment by autoSteve** [comment]
I've no idea why this happened...

image

**Review by BJReplay — COMMENTED** [review]
Thanks for additional editing.  Appreciated.

**Pull request merged**
