### PR TITLE
Post v4.0.41 2

### PR DESCRIPTION
**Pull request by autoSteve**
Prep in advance for v4.0.42.

We should give v4.0.41 time to settle before release.

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Review by BJReplay — COMMENTED** [review]
You, yes you, laddie.

**Comment by autoSteve** [comment]
I can keep the commits coming if you want... I am a pedant.

**Review by BJReplay — COMMENTED** [review]
My head hurts (literally), so I am turning off the PC and putting the phone down, but keep them coming.

**Comment by autoSteve** [comment]
Midnight local splines recalc timing still wants more work...

image

**Review by BJReplay — APPROVED** [review]
What version are you seeing the midnight jump in? I'm running .41, and I've not seen it.

image

**Comment by autoSteve** [comment]
Yeah, .41

It didn't happen all the time. There were two async timers that at midnight would both fire. If the spline recalc got in first then all was tickety-boo. If the sensor updates snuck in first then the jump occurs.

The last commit piggy-backs onto the top of the function that updates the sensors, meaning that they cannot update unless the splines are done.

**Review by BJReplay — APPROVED** [review]
42

**Comment by autoSteve** [comment]
_The_ answer. 42.

**Pull request merged**
