### PR TITLE
Three tries at rooftop sites, then fall-back to cache

### PR DESCRIPTION
**Pull request by autoSteve**
Like the description says, on startup try for three times to get the rooftop sites, with five second waits, and if these fail then fall back on previously cached sites data.

If a rooftop sites gather had been previously successful then the data from that gather will be used with a warning issued in the log.

#12

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
Gah. I based these code changes on v3, and not the v4 branch. I'll need to move the changes then kill this pull.

**Comment by autoSteve** [comment]
Actually, I'm confused, @BJReplay. "v3" is the default branch of the repo.

What's with the v4 branch?

**Comment by BJReplay** [comment]
> What's with the v4 branch?

I should delete it.  I had grand plans, but they went nowhere.  v3 is default.

**Comment by autoSteve** [comment]
> I had grand plans
😂

**Comment by BJReplay** [comment]
I was going to try to re-introduce automatic randomised polling based on user supplied API call limits. That's when I thought I had a round TUIT.

**Comment by BJReplay** [comment]
So is this good to go?

**Comment by autoSteve** [comment]
At the moment I'm looking at implementing a change mentioned in #12, @BJReplay. My intent is to recover from getting a 429 on forecast retrieve, by implementing an increasing timed back-off retry with a random number of seconds, i.e. 1m:26s, 2m:34s, 4m:02s. But only if the number of daily API calls is under the limit.

**Comment by BJReplay** [comment]
> At the moment I'm looking at implementing a change mentioned in #12, @BJReplay. My intent is to recover from getting a 429 on forecast retrieve, by implementing an increasing timed back-off retry with a random number of seconds, i.e. 1m:26s, 2m:34s, 4m:02s. But only if the number of daily API calls is under the limit.

@autoSteve you are a coding legend.  Thank you so much.  I'm squinting at my screen through my migraine so thankful that you're doing this.

**Review by BJReplay — APPROVED** [review]
Do you want to make the changes to manifest.json for the release, or keep running this for a day or so just to be sure it's working?

**Comment by autoSteve** [comment]
We _could_ release it as a beta. There were a lot of code changes, so that might be prudent.

@gcoan did lament that I hadn't released as a beta.

Then again, we could just send it! If folks have issue they could revert to 4.0.27 simply enough.

**Comment by BJReplay** [comment]
Given a) the sun is down (and my - and most people's automation) won't poll until after sunrise, and b) I'm barely on the right side of coping with this migraine my thought is to let in run through to tomorrow evening, and if things look good, cut a release then.

**Comment by autoSteve** [comment]
Sweet. You're the boss.

The Brits have woken up (and London is forecast rain... in Summer... top of 18... Lols...), so I'm sure @gcoan will pick up testing where our sun has failed.

**Comment by BJReplay** [comment]
You convinced me :)

**Comment by autoSteve** [comment]
> You convinced me :)

Send it. Gold.

**Comment by BJReplay** [comment]
I couldn't get it to show up in HACS tagged as a pre-release, so I updated it as latest.

**Comment by autoSteve** [comment]
Weird. Email says pre-release. Site says 4.0.28 latest... 🤷‍♂️

image

**Comment by gcoan** [comment]
Brilliant @BJReplay @autoSteve I'll load this 4.0.28 latest and turn debug on to check it's working fine.  Will rename the sites file first as well.

Yes I'm in the UK (about 70 miles North of London), the sun is allegedly up but we have a weekend of rain forecast.  So much for summer ☔️

**Comment by autoSteve** [comment]
@BJReplay, confused? Geoff has a sites.json file cache from an earlier commit, instead of a solcast-sites.json. I renamed it from oziee's original choice on his good recommend.

**Pull request merged**
