### PR TITLE
Fix check for conflicting integrations

### PR DESCRIPTION
**Pull request by autoSteve**
I have no words apart from, "Future analysis needed."

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Comment by BJReplay** [comment]
Sorry about the lag.

**Comment by BJReplay** [comment]
I have just deleted the Powerwall Integration.

Everything is now running from the cloud (which is probably what Elmo wanted, FFS).

**Comment by autoSteve** [comment]
Had to go to bed. Think I've fixed it, pending prod test. (In the air...)

**Comment by autoSteve** [comment]
Prod test checks out.

Gonna cut another v4.2.6 before the Europeans wake up.

**Comment by autoSteve** [comment]
That's a wrap. Much better.

**Pull request merged**
