### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by BJReplay**
Added details to the Bug report issue template including a request for logs and instructions for turning on debug logging, and a request for which version of the integration they're running

### CODE REVIEW

**Comment by autoSteve** [comment]
"Please include" might not be strong enough.

After waking up and seeing the silly things that people were doing (e.g. committing Solcast suicide and creating another key in the hope that would work, or downgrading/upgrading), I would say something like "always review logs prior to submitting an issue, and **always** attach debug level logging with an issue report unless the issue relates to a defect with the integration user interface".

**Comment by autoSteve** [comment]
A troubleshooting discussion (that is somehow locked for comments) might help, as folks are clearly not reading the readme.

**Comment by autoSteve** [comment]
From Google: "You can also lock a conversation to prevent comments on a discussion you want to use as an announcement to the community".

Then link the discussion in the issue report template?

**Comment by BJReplay** [comment]
I'm lucky I was reading that while in our weekly meeting so wasn't paying full attention to either the comments or the meeting, but FFS, people sacrificing chickens and reading the entrails and hoping that it works are why people like oziee cracked the shits and left.  I get it.

**Comment by BJReplay** [comment]
Bugger I can't edit the PR (or I can't work out how to edit the revised template).  I'll stick with the "please" for the moment.

**Comment by autoSteve** [comment]
You should be able to just add another commit to the PR, yeah?

**Comment by BJReplay** [comment]
Nah, because when you go to edit the templates, it edits on the main branch - I can't figure out how to get to the templates on the new branch.

**Review by autoSteve — APPROVED** [review]
Looks good as it is then

**Pull request merged**
