### PR TITLE
Post v4.2.6 fixes

### PR DESCRIPTION
**Pull request by autoSteve**
So far fix an "interesting" looking API key.

### CODE REVIEW

**Comment by autoSteve** [comment]
Re. #221. I am in a pleasing initial test state with this.

Conflict check looks for active entities `sensor.solcast_*` and barfs if any are found. Seems sensible and simple. If these sensors are there then a competing integration is deffo running as another name, not just lurking in the file system.

Sporadic testing will continue over the week.

Again, zero evidence = zero confidence that this is actually what we are chasing given the complexity of getting it set up.

**Review by BJReplay — APPROVED** [review]

**Comment by BJReplay** [comment]
This I **like**

Either all additions or all deletions.

image

**Comment by BJReplay** [comment]
Today is a good day to have a non-functioning solar system 0 didn't miss out on much forecast solar: hopefully just a damp rooftop isolator:

image

280kOhm resistance system to ground - must be > 500kOhm for the system to start.

Hopefully will dry out and be running tomorrow. 

Otherwise I'll be joining the queue of people trying to get new systems before the end of the year.

**Comment by autoSteve** [comment]
Yeah, you really didn't miss much. I peaked at 2.5kW AC with about 11.5kW AC capacity. Pretty much zero solar exports, with the only export being a super-peak period dump to offset the battery hitting zero early morning after an automation SNAFU yesterday. Still got paid.

Hope it's just moist.

image

**Comment by BJReplay** [comment]
> super-peak period dump

How are you managing to get your battery to dump?

Mine seems to want to power the house load from the grid when I have it set discharge to the grid so at best I end up with net zero and at worst it decides to pull from the grid and then power the house.

**Comment by autoSteve** [comment]
> How are you managing to get your battery to dump?

I set up the time of use periods in the PW app, and when I set to autonomous in the super-peak period it just starts exporting from PW plus powering house from it. House gets what it wants, grid gets everything else. (Reserve is set to zero at this time.)

There is weirdness that happens, but, and I have a case open with Tesla for that.

The TL>DR: PW dumps to grid at up to 10kW (because I have two). It should not, because the most United want me to push to grid is 5kW. They would get grumpy. Second, if house had been consuming 1kW then when the dump starts consumption will show as ~300W. This is not right, as no consumption has changed (I have servers, network, etc. that constantly pull at least 750W). Third, even if it is bright and sunny and solar was producing it will drop to zero during dump, or at lease show as zero because I don't know whether that actually happens.

So there are things wrong, but it works-ish. The charge level certainly drops in line with a 10kW dump.

For the money, it bloody well should "just work", so I'm a bit miffed at all the weirdness I have encountered thus far, and even more miffed with how log it seems to take anyone to take me seriously.

**Comment by autoSteve** [comment]
And this interests me...

While messing with retrying updates and removing / re-adding integration I managed to get two Solcast Solar integration instances apparently running. They weren't-ish. And I can't quite explain it, except that likely a task that had not been terminated was causing the just killed integration entry to hang around.

After the changes I have made I have not been able to replicate it, but it reminded me of recent reports of having two Solcast integrations "running" at the same time...

**Comment by BJReplay** [comment]
> After the changes I have made I have not been able to replicate it, but it reminded me of recent reports of having two Solcast integrations \"running\" at the same time...

If it walks like a duck?

**Comment by BJReplay** [comment]
> I set up the time of use periods in the PW app

Rates?

I used actual rates (more or less) - I wonder if that is the difference?

**Comment by autoSteve** [comment]
Screenshot_20241126_090845_Tesla
Screenshot_20241126_090941_Tesla

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
I've been getting the occasional dev environment warning about "long" running `__http_data_call()`, blocking for over 0.1 sec. It's refactored to be more async now, and I'll continue to monitor for further warnings.

**Comment by BJReplay** [comment]
> I've been getting the occasional dev environment warning about "long" running `__http_data_call()`, blocking for over 0.1 sec. It's refactored to be more async now, and I'll continue to monitor for further warnings.

```
2024-11-28 05:09:48.901 DEBUG (MainThread) [custom_components.epa_victoria_air_quality.coordinator] Finished fetching epa_victoria_air_quality data in 0.091 seconds (success: True)
2024-11-28 05:09:50.159 WARNING (MainThread) [asyncio] Executing <TimerHandle when=5310.65758079 EntityPlatform._async_handle_interval_callback() created at /workspaces/core/homeassistant/helpers/entity_platform.py:674> took 0.101 seconds
```

Personally, I think that's pretty good when the Postman call is 134ms, it's returning 94 sites, and I'm then sorting them by geographic distance from the HA installation 🤣 - but I am awaiting it in a a config flow, so I guess they can warn.

**Comment by BJReplay** [comment]
In other news, the solar system has bitten the dust, I think.  No generation since Sunday.  Just inspected the roof, hoping that I'd find a connector sitting in a puddle of water, or something obvious like that, but it's dry, but the inverter is still complaining about 3mA of residual current and insulation resistance of 250kOhm.  As low as 120kOhm in the morning, gets better during the day, so I assume that it is moisture related, but whether it is a dying module or something else, I don't know.  Just wasn't planning to try to replace it in a hurry this side of Christmas.  The good news is that if I'm not running the AC, I can go 21 hours without running on grid power 🤣 between 14:00 and 11:00 the next day.

**Comment by autoSteve** [comment]
> so I guess they can warn

If you've got some elements of that method that can be chonked up then just spin them up as awaited `asyncio.create_task()`s like I did with `apply_dampening()` and `sort_and_prune()`. That'll open up the main thread to continue unimpeded.

**Comment by autoSteve** [comment]
> the solar system has bitten the dust, I think

Damn.

Blessed be the "three free". Charge the battery and turn the house into a fridge with A/C on full! 😂.

**Comment by autoSteve** [comment]
> spin them up as awaited

Belay that, unless they utilise async library calls (which your code may well do, not looked). I've wound back use of create_task because it simply slowed things down, while appearing to make things better. Looking for other optimisations...

**Comment by autoSteve** [comment]
Here's another Python "trick" for you. Concurrent futures as an optimisation.

Async/await is cooperative multi-tasking using a single core. ThreadPoolExecutor spins up multiple threads on different cores for CPU-bound concurrent operations that may, or may not each also do async/await. These are independent of the main thread.

Code is in my prod, awaiting some further cycles. It's done a few, and then I ran out of API calls, as you do. Early result: it shaves off some update execution time, only seen in any significance with larger data sets like my prod, where forecast history > undampened forecast history. Significantly, the main thread continues un-blocked while the thread pool does its thing.

The positive impact? Minimal, given most folks update forecasts infrequently. The aim? Sink Solcast updates into the background as completely un-noticable from a main thread PoV.

**Comment by autoSteve** [comment]
By the way, the reason for only shaving off a whisker of processing time is the Python GIL (Global Interpreter Lock).

Python is inherently a do-one-thing-at-a-time proposition, mostly, which is quite the spoil sport. Multiple threads are spun up by concurrent futures, but this really only accelerates things when doing I/O bound processes and some other specialised cases that HA seems to not like, like Numpy (not general CPU-bound things like I said). I think that what is mostly going on here is lifting the burden off the main thread, so it does not complain about being slowed down, despite the slight speed gain overall, which is unintuitive but welcome.

I look forward to PEP 703 solving for this some day.

**Comment by autoSteve** [comment]
Be on the lookout for:

> WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.iris_north_east (<class 'custom_components.solcast_solar.sensor.RooftopSensor'>) took 0.469 seconds. Please create a bug report at https://github.com/BJReplay/ha-solcast-solar/issues

First time I've seen this. Happened about an hour after a forecast update, so not much Solcast going on. I've no idea why it took almost half a second. Equally I have no idea why it updated at all, as this should not be one of the every-five-minute sensors and should only update on forecast fetch and reload.

I'll double check all those sensor gubbins.

```
2024-11-30 13:08:40.944 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Task build_data took 0.157 seconds
2024-11-30 13:08:40.986 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Forecast data from 2024-11-30 to 2024-12-07 contains all intervals
2024-11-30 13:08:40.996 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Task recalculate_splines took 0.010 seconds
2024-11-30 13:08:41.114 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Saved dampened forecast cache
2024-11-30 13:08:41.127 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Saved un-dampened forecast cache
2024-11-30 13:08:41.127 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Forecast update completed successfully, next auto update at 16:48:04
2024-11-30 13:08:41.139 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Completed task pending_update_219
2024-11-30 14:10:00.774 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.iris_north_east (<class 'custom_components.solcast_solar.sensor.RooftopSensor'>) took 0.469 seconds. Please create a bug report at https://github.com/BJReplay/ha-solcast-solar/issues
```

**Comment by BJReplay** [comment]
> Be on the lookout for:

Only yellow or red in my logs are for TUYA or TESLA respectively.

Stand by for South East Water day after hourly water meter readings soon.  Currently scraping, considering hitting them up for an official API (but risking tipping off the scraping and risking the ban-hammer on that).

image

**Comment by autoSteve** [comment]
> hourly water meter readings soon

Wow. You've got a fancy water meter? Mine's dumb as a bag of hammers.

**Comment by autoSteve** [comment]
So... The site tally sensors/attributes are updating every five minutes. Actually, they are updating twice every five minutes and twice at forecast fetch.

I've not given that code any lovin', and what is being done makes no sense to do.

Oziee (I think, need to dig back in time) had an on-unload rigged to add a listener for some reason in the added-to-hass code. For why I don't know, but it is this that is causing the double-up. The every-five-minutes thing is because Isorin did not focus on the site sensors, only the bulk, hence the sensor update policy does not extend to updates of them.

I'm trialling the following modifications, looking for any down-side. Removed the on-remove, added check for date/data updated change.

The odd half-second update got me weirded out. It may be something to do with the on-remove head-bend.

```
    async def async_added_to_hass(self):
        """Entity is added to Home Assistant."""
        await super().async_added_to_hass()
        # self.async_on_remove(self._coordinator.async_add_listener(self._handle_coordinator_update))

    @callback
    def _handle_coordinator_update(self):
        """Handle updated data from the coordinator."""
        if not (self._coordinator.get_date_changed() or self._coordinator.get_data_updated()):
            return
        try:
            # _LOGGER.debug("Updating sensor %s, %s", self.entity_description.name, self._key)
            self._sensor_data = self._coordinator.get_site_sensor_value(self._rooftop_id, self._key)
        except Exception as e:  # noqa: BLE001
            _LOGGER.error("Unable to get sensor value: %s: %s", e, traceback.format_exc())
            self._sensor_data = None
        self.async_write_ha_state()
```

**Comment by autoSteve** [comment]
Yeah. That code goes well back to Oziee days... This from Dehumanizer77's fork. I can not wrap my head around why one would do this.

```
    async def async_added_to_hass(self) -> None:
        """When entity is added to hass."""
        await super().async_added_to_hass()
        self.async_on_remove(
            self.coordinator.async_add_listener(self._handle_coordinator_update)
        )
```

**Comment by BJReplay** [comment]
> Wow. You've got a fancy water meter? Mine's dumb as a bag of hammers.

Only just arrived (on the 27th.  Hourly readings.  Talks over vodaphone to Salesforce.  Ugly as sin user portal.  I'm trying to learn javascript and have just discovered that you can't define functions outside of executes because they get passed in as strings.  So, I have to copy-pasta a big ugly piece of string manipulation because I need it twice, rather than put it in a function, because it needs to be passed into puppeteer.

> I'm trialling the following modifications, looking for any down-side. Removed the on-remove, added check for date/data updated change.

See, that works, you work on stuff you have a chance of understanding, and I'll work on stuff I have no chance of understanding, used by zero people, so when it breaks, it affects no-one.

```
  browserless.io:limiter:error  BadRequest: ReferenceError: getUsage is not defined
evaluate (evaluate at default (http://0.0.0.0:3000/function/browserless-function-ccfcd69c-aece-40ba-bebb-37c551b8f084.js:69:37), <anonymous>:1:4)
#evaluate (http://0.0.0.0:3000/function/index.html:13914:15)
async ExecutionContext.evaluate (http://0.0.0.0:3000/function/index.html:13810:14)
async IsolatedWorld.evaluate (http://0.0.0.0:3000/function/index.html:14660:14)
async CdpFrame.evaluate (http://0.0.0.0:3000/function/index.html:11152:16)
async _CdpPage.evaluate (http://0.0.0.0:3000/function/index.html:7607:16)
    at file:///usr/src/app/build/shared/utils/function/handler.js:90:15
    at async file:///usr/src/app/build/shared/utils/function/handler.js:71:38
    at async ChromiumFunctionPostRoute.handler (file:///usr/src/app/build/shared/function.http.js:24:48)
    at async file:///usr/src/app/build/router.js:60:28
    at async bound (file:///usr/src/app/build/limiter.js:136:36) +7m
 
```

**Comment by autoSteve** [comment]
> I'll work on stuff I have no chance of understanding

Trail blaze, my friend. You may have a +1 for JavaScript if I can can get my hands on one of those puppys. It's been a while, but because ServiceNow I'm somewhat versed.

Vodafail? Could be worse. Floptus haven't acquitted themselves very well of late, especially for bank. Dropped both cross-sites for 15 seconds, which is an eternity in the world of cross-site, resulting in 10pm-6am work for quite a lot of folk, and much WTF? later. Honestly, who yearns for Telstra again? Bank storage and Unix teams.

> Ugly as sin user portal

🤣

So did you get a notification of install happening, or did you seek out the shiny digital water thing?

**Comment by BJReplay** [comment]
> So did you get a notification of install happening, or did you seek out the shiny digital water thing?

Kinda both, I think.  I suspect I ticked

- [X] I'm interested in a digital meter

years ago and then got a letter saying they were rolling them out, but when I asked the guy, he said they were just rolling them out to a few in the street.  Not mesh, individual VF modems.

> Dropped both cross-sites for 15 seconds

FFS.

Back in the day, when Telstra dropped two redundant fibre paths to a power station, the IT guys said F#%@ it, we'll show you what redundancy is, and:

- Put in Optus, VodaFail and Telstra 4G (probably 3G initially) failover x 2 at each redundant control room.  There were 8 paths back to 2 live and 2 backup data centres, including the fibre.   
- Churned to someone reselling Telstra fibre, since that's all there was.  Cheaper, not Telstra.  Sorta felt good for the IT guys for the last step.
- Churned all telco to Optarse

When the Telstra account manager asked why, showed them the RRDtool graph of connectivity, and the market notice for the breach for failing to start.

Gas peakers need to start within five minutes if the market instructs them to do so.

6 WLAN aerials on the top of each cabinet in the control rooms was a giggle.

If you're annoyed by the fact that your dev container timezone is wrong, have a look at this piece of magic that I just discovered:  https://hwaien.com/2023/04/13/dev-container-time-zone.html - I went with the first option - editing devcontainer.json before reading further and discovering that I could just edit settings.json.

**Comment by BJReplay** [comment]
> Be on the lookout for:

Just saw this pop up in my Dev Container...

`2024-12-01 14:50:00.286 WARNING (MainThread) [asyncio] Executing <TimerHandle when=16603.212547302246 _TrackPointUTCTime(hass=<HomeAssistant RUNNING>, job=<Job time change listener None:range(0, 60, 5):0 <bound method SolcastUpdateCoordinator.update_integration_listeners of <custom_components.solcast_solar.coordinator.SolcastUpdateCoordinator object at 0x7fb355337380>> HassJobType.Callback <bound method _TrackUTCTimeChange._pattern_time_change_listener of _TrackUTCTimeChange(hass=<HomeAssistant RUNNING>, time_match_expression=([0], [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), microsecond=172109, local=False, job=<Job track time change None:range(0, 60, 5):0 local=False HassJobType.Coroutinefunction <bound method SolcastUpdateCoordinator.update_integration_listeners of <custom_components.solcast_solar.coordinator.SolcastUpdateCoordinator object at 0x7fb355337380>>>, listener_job_name='time change listener None:range(0, 60, 5):0 <bound method SolcastUpdateCoordinator.update_integration_listeners of <custom_components.solcast_solar.coordinator.SolcastUpdateCoordinator object at 0x7fb355337380>>', _pattern_time_change_listener_job=<Job time change listener None:range(0, 60, 5):0 <bound method SolcastUpdateCoordinator.update_integration_listeners of <custom_components.solcast_solar.coordinator.SolcastUpdateCoordinator object at 0x7fb355337380>> HassJobType.Callback <bound method _TrackUTCTimeChange._pattern_time_change_listener of ...>>, _cancel_callback=<bound method _TrackPointUTCTime.async_cancel of _TrackPointUTCTime(hass=<HomeAssistant RUNNING>, job=<Job time change listener None:range(0, 60, 5):0 <bound method SolcastUpdateCoordinator.update_integration_listeners of <custom_components.solcast_solar.coordinator.SolcastUpdateCoordinator object at 0x7fb355337380>> HassJobType.Callback <bound method _TrackUTCTimeChange._pattern_time_change_listener of ...>>, utc_point_in_time=datetime.datetime(2024, 12, 1, 3, 55, 0, 172109, tzinfo=datetime.timezone.utc), expected_fire_timestamp=1733025300.172109, _cancel_callback=<TimerHandle when=16903.21254348755 ...() created at /workspaces/core/homeassistant/helpers/event.py:1506>)>)>>, utc_point_in_time=datetime.datetime(2024, 12, 1, 3, 50, 0, 172109, tzinfo=datetime.timezone.utc), expected_fire_timestamp=1733025000.172109, _cancel_callback=<TimerHandle when=16603.212547302246 ...() created at /workspaces/core/homeassistant/helpers/event.py:1506>)() created at /workspaces/core/homeassistant/helpers/event.py:1506> took 0.111 seconds`

Wasn't actually doing anything (I was trying to grok some config flow code).

Dev container started at 14:47, so it was the first five-minute interval to fire.

While I've been typing this, the second five-minute interval has been and gone with nothing logged.

**Comment by autoSteve** [comment]
Latest commit removing the call to async_on_remove() seems to make things just better. The rooftop sensor(s) are update on fetch/day change, and I've unsurprisingly not seen another half second sensor update (which was just weird given how simple that code section is).

> took 0.111 seconds

Equally weird, given the per-five-minute only updates eight sensors. I don't think the odd slow update is that bad becase tenth of a second, just weird and no fault of the integration. An update of all sensors usually takes ~0.012 seconds.

**Comment by autoSteve** [comment]
After a week of on-and-off examining and poking and questioning, I'm happy if you are to unleash the mini-beast that shall become known as v4.2.7...

I shall continue to monitor tomoz, but prod looks happy as a clam. Dev does what dev does. Rinse and repeat rapidly.

**Comment by BJReplay** [comment]
> After a week of on-and-off examining and poking and questioning, I'm happy if you are to unleash the mini-beast that shall become known as v4.2.7...

Sounds like a plan.

**Comment by autoSteve** [comment]
How's ya solar?

(Rebases and merges...)

**Comment by autoSteve** [comment]
Well, v4.2.7 is free. Brace for impact, my friend... (Although I don't think I've stuffed anything up given runtime.)

**Comment by autoSteve** [comment]
Hang on... Where did v4.2.6 go???

**Comment by BJReplay** [comment]
See notes in 4.2.7 just added.

To avoid HACS caching the last release, and grief where people get tripped up.

**Comment by BJReplay** [comment]
> Hang on... Where did v4.2.6 go???

I used my powers to blow the little bomb that might catch someone later up in a controlled explosion.

**Comment by BJReplay** [comment]
OK.  Nice.  So back to my South East Water integration.  

Next will be integrating OCPP charger control with excess solar to control feeding in excess into the EV.

I have it working with a simulator (simulated charger), working of simulated solar (thanks, Solcast).  I've got a new habit to feed.

**Comment by autoSteve** [comment]
If this release is stable, touch wood, then I reakon we could race HACS DB publish to actually get into HA core before that happens, after building the required config/options flow Py tests... 🖕

We're five pages down in the queue, which is moving at GLACIAL pace. Caught up to Feb '24 I think, which I thought was a blessing now that we're actually in the "new" year, which is almost over. Gah! It'll be "next year" quite soon. The rate we're goin' you and I will be dead before included in HACS.

Dare I say it, I reakon we could reach top tier HA core component quality recog. before an eventual HACS publish some time in **_2026_**...

**Comment by BJReplay** [comment]
Given your testing harness work - which I still haven't run 🫢 - yes, probably. It is pretty stable.

**Pull request merged**
