### PR TITLE
Forecast fail to retrieve handling fixes

### PR DESCRIPTION
**Pull request by autoSteve**
As the title says, when bad stuff happens bad stuff can happen.

This PR fixes two potential bad happenings.

### CODE REVIEW

**Comment by autoSteve** [comment]
It is deffo not worthy of a release, so save it up. As long as Solcast behave themselves.

**Review by BJReplay — APPROVED** [review]
Disappointed not to see 418 as the status code.

**Comment by autoSteve** [comment]
🤣🤣🤣

**Comment by autoSteve** [comment]
An opportunity missed...

**Pull request merged**
