### PR TITLE
Dampening calculation improvements

### PR DESCRIPTION
**Pull request by isorin**
1) Change the way dampening factors are applied
Apply the dampening factors directly to the forecasts received from Solcast (when the data is updated) instead of applying them at load time (which by the way includes all forecast history).
One other problem with applying them at load time, apart from being inefficient, is the fact that we apply the current values of dampening factors to all of the history which doesn't take into account the fact that the dampening factors change over time.

2) Added the ability to load dampening factors per site from a json file
The json file can contain either 24 values (hourly values) or 48 values (30 minutes values) which align with the forecasts received from Solcast and make the calculation of dampening more accurate.
The structure of the json file is like this:
{
    "siteA-substring": [list-of-dampening-factors-for-siteA],
    "siteB-substring": [list-of-dampening-factors-for-siteB],
    "siteC-substring": [list-of-dampening-factors-for-siteC],
}
where siteX-substring is any substring that can uniquely identify siteA resource_id as defined in Solcast.

If the file doesn't exist, the existing dampening factors loaded through the service call are applied.

Note:
We could also update the config and the service that loads the dampening factors to allow per site factors and/or per-hour/per-30mins values but that can be a separate PR.

I've been using these changes for a few weeks now.
I generate the dampening factors file daily (before the 1st Solcast update) with a Python script.

### CODE REVIEW

**Comment by isorin** [comment]
Caching up with recent changes in your PR @autoSteve 
Maybe we find a way to put together the two.
I had mine ready for some time but couldn't find the time to upload the changes here.

**Comment by BJReplay** [comment]
@isorin, as you can probably see,  @autoSteve has enabled site level dampening in https://github.com/BJReplay/ha-solcast-solar/pull/165 that we are close to releasing as a pre-release. 

Your changes are a good addition - 1/2 hourly (though that probably is overkill for many), and the idea of applying on retrieval of the raw forecast seems appealing. File loading also seems valuable.

Steve has done all the hard work on this PR,  so I will leave it to him to determine whether or not he will consider your PR (perhaps against  https://github.com/autoSteve/ha-solcast-solar/tree/Detailed-forecast-sites-breakdown) ahead of v4.1.8 pre-release.

**Comment by autoSteve** [comment]
I really like the shift to set dampening in __http_data_call() @isorin. This makes perfect sense.

I also like the flexibility of being able to set site dampening from a .json file, as too do I like the service call modification that I've implemented to set per-site. These can live happily together, because they achieve the same thing in a different way. File exists? Load it. Service call? Load it.

I was a whisker away from sending v4.1.8, but spotted some annoying aspects relating to avoiding integration reload after options flow, so fixed that today. There's even a draft release created...

But these ideas have merit, and I want to embrace them because they are most complimentary.

So how to embrace these changes?

A possibility is merge my proposed @autoSteve v4.1.8 PR into @BJReplay's repo, then you re-base your PR and work though conflicts. Or I could directly add your changes to my PR pre-merge.

To cope with a post-merge re-base we do have some class variable naming differences though. I chose the `SolcastApi.site_damp` public dict and not protected (like your `_damp_sites`), because set outside the class by the `__init__` service handler.

(Famous last words) I am confident that I have my PR sorted now. So we could take the merge/re-base approach, but there's re-work for you.

Thoughts?

**Comment by isorin** [comment]
@BJReplay @autoSteve 
Yeah, up to Steve to decide!
We can definitively go with v4.1.8 first and leave this PR for after.

per-site and per-30 minutes are a must and not overkill at all.
The hourly factors are kind of useless (very imprecise) so no, the 30-minutes factors defo not overkill.

**Comment by autoSteve** [comment]
> the 30-minutes factors defo not overkill.

IKR? It's just unmanagable from an options flow point-of view currently, and @BJReplay actually uses that.

Does this entirely get dropped from options flow? @BJReplay would probably disagree...

Are there separate service calls created to set per-half-hour dampening if that's your thing, which would overrule hourly?

**Comment by autoSteve** [comment]
Theory of operation of my site dampening handling:

* If file exists, load on startup
* If service call for a site sets site dampening then serialise
* If subsequent service call for a different site then set site dampening then serialise
* If overall all-sites dampening gets set (options flow, or service call) then kill the per-site dampening, including file drop.
* When applying dampening, if per-site dict has content, use that, eles use all-sites.

**Comment by isorin** [comment]
I looked at config and service call as well and I said I wouldn't bother updating it (and then maintaining it too) for the 30-minutes factors.
That's why I went with the file approach.
More flexibility, easier to integrate and it is persistent - no need to save the dampening factors as config.

There are a lot of changes in 4.1.8 - it is up to you Steve but I would say to leave my changes for after 4.1.8.
We can rebase and update the PR no problem.

Btw. in my implementation, I look at the modification time of the file and load it (if needed) before dampening is applied.
If the file is present / loaded, then it overrides the dampening factors set in the config / service call.

**Comment by isorin** [comment]
> As to the specifics of how to add half-hourly, whether overall or per-site... Is it the same service calls/files, just with a different number of list elements? 😅🤔 (That hasn't got f*ck up written all over it, has it???)

Yes, same file structure, either 24 or 48 elements in the list:
`
  zz = z.astimezone(self._tz)
  dx = zz.hour
  if len(_damp) >= 48:
      dx = zz.hour * 2 + (1 if zz.minute >= 30 else 0)
`

**Comment by isorin** [comment]
Btw. I like the idea of serializing the data from the service call, store the dampening factors in a file and remove them from the config.
Do we still need to provide input through the UI to load them?
Otherwise it could just be the json blob directly which we can validate and dump in the file.

**Comment by Nilogax** [comment]
Quick question on this.  My damping calcs rely on resetting to an undamped Solcast forecast (ie all damping factors are 1's) so I can compare tbat with actual generation to determine new factors.  Would that still be viable under this proposal?  Plan B would be to skip the damping reset then scale the existing damping factors based on damped forecast vs actual.  That obviously relies on knowing the current factors which aren't presently exposed by the Solcast integration but I think it's a one day issue as after the first run my solution preserves the last factors it applied so I'd work from them.   Not really a biggie in itself, just means the forecast that's probably wrong might be slightly more wrong for a day.

**Comment by autoSteve** [comment]
Tossing an idea out there, @Nilogax, if you were to have the undampened detailed forecast data as an additional attribute that would solve for it, yes? That way you would not need to reset dampening to default, just read from a different attribute.

One extra tick-box in config, default off. No recorder database bloat because any additional large attributes would be tossed away. Further Urdu translations (😭).

**Comment by Nilogax** [comment]
Yep that'd work thanks - though rather than adding to config the damped/undamped selection could be a parameter in the query_forecast_data service? Still needs Urdu though :) 

TBH I was surprised at the way the integration recalculated historic data but it proved useful. Might be worth flagging this PR as a potentially breaking change in case anyone else relies on the old behaviour.

**Comment by autoSteve** [comment]
> could be a parameter in the query_forecast_data service?

Good idea. It could be both. Tossing things out there to see what sticks.

If you and others would just utilise service call return data for this kind of advanced use case, then that would be simpler to implement, and not require an entry options version bump. This would be my preferred implementation, not attributes.

> Urdu

If it's both, then I'll have my head in copy-from-right-of-screen / add spaces / paste / remove spaces mode anyway.

I might start a poll to see who's actually using the Urdu translation, and also whether they're reading gibberish. I got nothin' and no feedback, despite messing with a lot of Urdu of late...

**Comment by autoSteve** [comment]
@isorin, my thoughts on having one's cake and eating it too here, i.e. have both dampened data make its way into solcast.json and be efficient, plus have un-dampened forecast available we'll likely need a `solcast-raw.json` of similar/same structure to `solcast.json` also serialised from an in-memory dict.

This could be trimmed to two weeks (?) retention, fulfilling @Nilogax's use case. The useful lifetime of undampened data would be short, so the memory requirement and storage needs small.

__serialize_data() could add parameters for the data set and file to write. Easy

load_saved_data() half did my head in whilst contemplating this, though, with regard to sites added/removed. Because large `with aiofiles.open()` block it would need re-work.

I've not yet dived further, but to have both is going to end up being a significant change with extensive testing required.

Unless you can see a simpler way.

**Comment by Nilogax** [comment]
Two weeks is more than enough for my use case thanks. 

Thought on config vs service - if someone wants undamped current or future data surely they can just reset the factors and all is gravy. It's only an issue if some awkward cuss wants undamped history and the only way to get that is via the service call, hence no need for config (in any language). Yay or nay?

**Comment by autoSteve** [comment]
@Nilogax, @BJReplay will invite you to be a collaborator here.

I will spin up a branch at BJ's fork for us to colab on this excellent suggestion, with you sending any commits to the upstream branch.

Does that work for you?

**Comment by autoSteve** [comment]
> Because large `with aiofiles.open()` block it would need re-work.

It has already seen re-work to undo the large `with aiofiles.open()` block, which was just wrong for the future, and just wrong in other ways. Sorry.

Done pre-merge of #165, which is now released as a pre-release v4.1.8.

**Comment by BJReplay** [comment]
Invites sent to @isorin and @Nilogax

**Comment by autoSteve** [comment]
> reset damping factors just before midnight

I assume you have a scheduled fetch at midnight. That'd work. It's messed up MacGyver stuff, but it'd work with that duct tape solution... (And no Urdu. High-five!) Then next fetch would apply your calculated dampening I presume, given @isorin's proposal of shifting that calc to forecast fetch, not on dampening set.

**Comment by Nilogax** [comment]
_It's messed up MacGyver stuff_

I'll take that as a compliment!

OK will start fiddling with my code, this approach should work with the current release so no need to wait.

**Comment by isorin** [comment]
Sorry, got side-tracked with some work.
@autoSteve Sounds perfect to me! 🙂

**Comment by BJReplay** [comment]
> Setting overall per-hour dampening by service call or by options flow would delete the file.

Setting overall per-hour dampening by service call or by options flow would _rename the file_ to (something like) service_override.yyyymmdd-hhmmss.mmmUTC

Why?

Recoverability.

Testing.

**Comment by autoSteve** [comment]
> service call or by options flow would rename the file

I like this, but not the datetime aspect. Files already have atime/mtime, so renaming to `...json.old` may be enough (and removing prior old before doing so). Several generations might be overkill but could also be done. Kind of like how syslog does it.

**Comment by BJReplay** [comment]
Agreed.

**Comment by autoSteve** [comment]
Closing and continuing over at #178.

**Pull request closed without merging**
