### PR TITLE
v4.1

### PR DESCRIPTION
**Pull request by BJReplay**
Get ready for v4.1

### CODE REVIEW

**Comment by BJReplay** [comment]
Feel free to fix any and all typos, poor phraseology, etc.

**Comment by autoSteve** [comment]
Your PR, so you can't review your own work, but do give my readme re-org a look over.

**Review by autoSteve — APPROVED** [review]

**Comment by BJReplay** [comment]
I'm going to cut a release.  Unless you shout loudly, fairly quickly.

**Comment by autoSteve** [comment]
Typo. Fixing.

**Pull request merged**
