### PR TITLE
Api quota and retries

### PR DESCRIPTION
**Pull request by autoSteve**
WIP.

The new config option is added for API quota, and this is implemented to be used, retiring the API call.

A config upgrade from v8 to v9 will get the values currently set in cache file(s), and use this/these as the config entry value(s) without needing to set it.

I have not tested a completely new install, but probs works.

I have not tested my Urdu translations. Obviously. And will not.

To do is to think about the retry situation.

### CODE REVIEW

**Comment by autoSteve** [comment]
I am thinking that our fledgeling v4.1.3 needs to be a beta, @BJReplay, because because. Then release a latest as v4.1.4 if folks are pleased, having the changelog v4.1.2..v4.1.4.

v4.1.4 is nicely symmetrical. And four is an even number. I like it. It will be a good release because superstition... (With no payload other than a manifest/readme update, a new discussion and a 'ta-da!') We can leave the beta discussion on the v4.1.2 thread, alerting the usual vocal crew with mentions there.

**Comment by autoSteve** [comment]
I chickened out for now on refactoring retries, just made them more aggressive 😡 over fifteen minutes instead. On to a brand new install test...

**Review by BJReplay — APPROVED** [review]
Agree re beta. We can promote to release or cut a new one as needed depending on whether or not other things occur.

What is the best way to test the upgrade? Just install?

**Comment by autoSteve** [comment]
If you want to test this, then go right ahead. You'll need to pull all files changed on the branch, shove them in the Solcast custom component directory, then restart to test an in-place upgrade. You'll need `en.json` from `translations/` only.

For a new install I'm about to take a snapshot of my production rig, then kill off Solcast, including all remnants in /config, and then install afresh. Take one for the team: API call usage be damned... Then slink back to the snapshot, hopefully without tail between legs. (While writing this I might just clone my prod, suspend it, start clone, have at, then drop the clone and resume prod., which will be potentially less destructive...)

**Comment by BJReplay** [comment]
Ok, probably one for tomorrow.

**Comment by autoSteve** [comment]
Well that was and interesting "ground zero" test. One quick code hack later, and four API calls, and it was operational.

But... the integration should now ask for both an API key and an API quota on install (with default of ten). It didn't. Just the API key. The default of ten-per-API-key was completely silent.

So more work to nut out why that happened.

Home Assistant is quite quirky at times...

**Comment by autoSteve** [comment]
That'll do it... I missed a bit. Blue bits for the win. #retest

image

**Comment by autoSteve** [comment]
New install FOR. THE. WIN...!

image

**Comment by autoSteve** [comment]
BTW, if a multiple-API-key-comma-separated user then enters just one API quota value then that value will be used for all API keys. I'm well ahead of that lot stuffing up...

**Comment by autoSteve** [comment]
Readme is to do.

**Comment by BJReplay** [comment]
```
homeassistant  | 2024-08-16 09:25:57.146 DEBUG (MainThread) [custom_components.solcast_solar] Options version 8
homeassistant  | 2024-08-16 09:25:57.150 DEBUG (MainThread) [custom_components.solcast_solar] Upgraded to options version 9
homeassistant  | 2024-08-16 09:25:57.152 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Configuration directory is /config
homeassistant  | 2024-08-16 09:25:57.152 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Sites cache exists
homeassistant  | 2024-08-16 09:25:57.152 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Connecting to https://api.solcast.com.au/rooftop_sites?format=json&api_key=******NFkfQM
homeassistant  | 2024-08-16 09:25:57.668 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] HTTP session returned status 200/Success in sites_data()
homeassistant  | 2024-08-16 09:25:57.668 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Writing sites cache
homeassistant  | 2024-08-16 09:25:57.679 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Sites data: {'sites': [{'name': 'yada', 'resource_id': '3f77-yada-yada-b925', 'capacity': 5, 'capacity_dc': 4.85, 'longitude': **.******, 'latitude': **.******, 'azimuth': -123, 'tilt': 5, 'install_date': '2012-04-18T14:00:00.0000000Z', 'loss_factor': 0.9, 'tags': ['Home ', 'Map 57']}], 'page_count': 1, 'current_page': 1, 'total_records': 1}
homeassistant  | 2024-08-16 09:25:57.679 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Getting API usage from cache for API key ******NFkfQM
homeassistant  | 2024-08-16 09:25:57.680 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API usage cache exists
homeassistant  | 2024-08-16 09:25:57.694 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API usage cache loaded
homeassistant  | 2024-08-16 09:25:57.694 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] API counter for ******NFkfQM is 7/50
homeassistant  | 2024-08-16 09:25:57.756 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] The saved data file exists, file type is <class 'dict'>
homeassistant  | 2024-08-16 09:25:57.832 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Calc forecast start index midnight: 2024-08-15 14:00:00 UTC, idx 4078, len 4463
homeassistant  | 2024-08-16 09:25:57.855 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-16 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.855 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-17 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.855 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-18 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.856 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-19 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.856 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-20 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.856 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-21 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.857 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-22 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.857 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Data for 2024-08-23 contains all 48 records
homeassistant  | 2024-08-16 09:25:57.857 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Calculating splines
homeassistant  | 2024-08-16 09:25:57.877 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Build forecast processing took 0.1204s
homeassistant  | 2024-08-16 09:25:57.877 INFO (MainThread) [custom_components.solcast_solar.solcastapi] Loaded solcast.json forecast cache
homeassistant  | 2024-08-16 09:25:57.893 INFO (MainThread) [custom_components.solcast_solar]
homeassistant  | -------------------------------------------------------------------
homeassistant  | Solcast integration version: v4.1.2
homeassistant  |
homeassistant  | This is a custom integration. When troubleshooting a problem, after
homeassistant  | reviewing open and closed issues, and the discussions, check the
homeassistant  | required automation is functioning correctly and try enabling debug
homeassistant  | logging to see more. Troubleshooting tips available at:
homeassistant  | https://github.com/BJReplay/ha-solcast-solar/discussions/38
homeassistant  |
homeassistant  | Beta versions may also have addressed some issues so look at those.
homeassistant  |
homeassistant  | If all else fails, then open an issue and our community will try to
homeassistant  | help: https://github.com/BJReplay/ha-solcast-solar/issues
homeassistant  | -------------------------------------------------------------------
homeassistant  | 2024-08-16 09:25:57.893 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Finished fetching solcast_solar data in 0.000 seconds (success: True)
homeassistant  | 2024-08-16 09:25:58.042 DEBUG (MainThread) [custom_components.solcast_solar] UTC times are converted to Australia/Sydney
```

Once I copied all files (left out const.py first time), worked.

Correctly shows my API count as cached from last successful API call.

I personally think this doesn't need a beta release, or if it is beta, is upgraded from beta to non-beta fairly quickly.

**Comment by autoSteve** [comment]
Fair enough re. beta.

I've added an examination of the payload returned when 429s occur, looking for API quota exhaustion. If it is seen, then the usage cache gets updated to where it should be, not where it thinks it is.

As a test, later on today I will intentionally reach quota by executing some `curl`s outside of the integration, then manually fire a fetch forecast to verify that this exam works.

**Comment by BJReplay** [comment]
I've pulled in that change (but not tried to exhaust my API count (as it is 50) so the happy case works.

**Comment by autoSteve** [comment]
Sweet.

I've just drained the quota, and it mostly works, picking up that use is exhausted. I'll make a couple more tweaks to make the logged experience is better.

**Comment by autoSteve** [comment]
One circumstance that I have not been able to test is a genuine 'try again later' / 'we're busy' scenario.

Given you have not run out of quota it'd be great if you could check your logs for any of those.

**Comment by autoSteve** [comment]
> Sites data: {'sites': [{'name': 'yada', 'resource_id': '3f77-yada-yada-b925', ...

Lols. Just noticed your yada yadas. Maybe we should do the log redactions like that... 😂

**Comment by BJReplay** [comment]
> Lols. Just noticed your yada yadas. Maybe we should do the log redactions like that...

Given that it's a function, it is possible.  I replaced things that probably didn't need to be replaced and others with Melways references.

**Comment by BJReplay** [comment]
OK for release (beta or non-beta as you prefer) whenever you want - I've reviewed it all and am running it) and am happy with the code.  And people can roll back (or we can turn on the beta flag if needed.

**Comment by autoSteve** [comment]
But the hex of the odd numbered release... Must... not... (Ah, b*gger it!)

Sending it as latest. The Europeans are awake and there's plenty of issue anwering time left. And it's a Friday.

We got to 1,647 4.1.2 downloads. (whinging) _I wanna know where the number will stop at!_ Stupid API change...

**Comment by BJReplay** [comment]
The sawtooth continues...

image

**Comment by autoSteve** [comment]
I just fixed a typo in the release, so add five in your head to the current tally.

The daily Europe stall is hysterical. Reminds me of the stupid splines that Apex charts does.

**Comment by BJReplay** [comment]
> We got to 1,647 4.1.2 downloads. (whinging) _I wanna know where the number will stop at!_ Stupid API change...

It's interesting, isn't it?  I'm guessing there's a reasonable number of people who won't see the little notification number on their settings icon on their HA install that won't know for some time that there's a release to install.

**Comment by autoSteve** [comment]
And clearly they don't check logs or restart that often!

**Comment by BJReplay** [comment]
1666 total for 4.1.2

**Pull request merged**
