### PR TITLE
Fixes #8 #9 #10 - My HA Button category

### LINKED ISSUE #8: Fix My Home assistant button
**Describe the bug**
The my home assistant button in the readme registers the repository as `plugin` which seems to register it as Lovelace widget.

**To Reproduce**
1. Click on the my home assistant button
2. Follow the instructions on screen
3. You will find the integration in the Lovelace widgets

**Expected behavior**
The repository is added under integratons

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 14
 - Browser: HA App
 - Version: Latest from play store

**Additional context**
You probably only have to change the type in the URL to `integration`

### PR DESCRIPTION
**Pull request by mZ738**
Change My Home Assistant Link Repo Type to integration

### CODE REVIEW

**Review by cromefire — APPROVED** [review]
The new link seems to work fine (not that I'm able to give it the go ahead, but still I tested it)

**Comment by cromefire** [comment]
You might wanna give the PR a more meaningful title though, modifying the readme could be basically anything, and you can also like the respective issues with `
Fixes #<issue number>`, so they get automatically closed on merge.

**Comment by mZ738** [comment]
> You might wanna give the PR a more meaningful title though, modifying the readme could be basically anything, and you can also link the respective issues with `
> Fixes #<issue number>`, so they get automatically closed on merge.

Yes thanks for the hint. Just created the PR on the Phone :)

**Comment by BJReplay** [comment]
Thank You!

I will accept this PR, but don't want to break the PR trying to get this into HACS, so will sit on it until HACS process complete, then merge.

**Comment by cromefire** [comment]
> > You might wanna give the PR a more meaningful title though, modifying the readme could be basically anything, and you can also link the respective issues with `
> > Fixes #<issue number>`, so they get automatically closed on merge.
> 
> Yes thanks for the hint. Just created the PR on the Phone :) 

It's sufficient btw to write the `Fixes #` in the issue description. Then when you hover over it in the preview it'll also tell you that it'll close that issue. And you can't chain them I believe and you have to repeat that phrase every time (but there's also github docs explaining it in more detail).

**Pull request merged**
