### PR TITLE
V4.1.4 release prep

### PR DESCRIPTION
**Pull request by autoSteve**

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]
Looks Good!  Will email OOC.

**Comment by autoSteve** [comment]
Drafted a v4.1.4 release.

You wanna do the honours?

**Comment by BJReplay** [comment]
> You wanna do the honours?

Unless you specifically don't, no, I think this is your masterpiece (and no, that's not tongue in cheek).

**Comment by BJReplay** [comment]
But ping me via email and I can upgrade the announcement if necessary, from general.

**Pull request merged**
