### PR TITLE
Use aiofiles with async open, await data_file

### PR DESCRIPTION
**Pull request by autoSteve**
The problem with using open is that this is a blocking function.

A solution can be found by utilising the 'aiofiles' library. This pull request changes the blocking open/read data file with an async aiofiles.open, along with an 'await'ed json.load() of the file.

The blocking message has disappeared for this integration for me, which makes complete sense.

Should solve #14.

### CODE REVIEW

**Comment by autoSteve** [comment]
There is more to this.

**Comment by autoSteve** [comment]
Early indications are good for me for proposed pull #21 using aiofiles. I am going to wait until the sun comes up and forecasts come in for further analysis. @BJReplay, #14.

**Comment by autoSteve** [comment]
This may require an "Await me maybe" logic to support earlier versions of HA. Not sure yet, @BJReplay.

**Comment by BJReplay** [comment]
> This may require an "Await me maybe" logic to support earlier versions of HA. Not sure yet, @BJReplay.

I would appreciate any information you can provide about this, @autoSteve !

**Comment by autoSteve** [comment]
On examining the need for "await maybe" I'm pretty sure using async/await always for aiofiles will be good. In all sections of the code that read/write files there are other uses of async.

I'll set this as ready for review, @BJReplay.

**Comment by BJReplay** [comment]
Thanks - can you confirm that you have run this code and it is working, and what version of HA it is running against?

Can you comment on whether this change is backwards compatible with earlier versions of HA?

**Comment by autoSteve** [comment]
This code is running on my HA. Version 2024.6.1, and just now updated to 2024.6.2 without issue.

My thinking is that earlier versions _should_ be okay with it. The solcastapi.py makes use of aiohttp for async REST calls, so switching to aiofiles is very much simpatico. I downgraded to 2023.11.3 as a bit of an extreme case, and all seems well.

**Comment by autoSteve** [comment]
You want I should remove all the surplus space characters everywhere to clean things up before merge, @BJReplay?

**Comment by BJReplay** [comment]
I won't say no!

Yes, that would be really appreciated.

**Comment by autoSteve** [comment]
@sh00t2kill and I are happy now. Excess space usage curtailed and committed, @BJReplay.

**Review by BJReplay — APPROVED** [review]

**Pull request merged**
