### PR TITLE
Fix for earlier HA versions not recognising version= for async_update_entry()

### PR DESCRIPTION
**Pull request by autoSteve**
For those weirdos on 'super' old versions that subscribe to the IBM philosophy of "if it ain't broke, don't poke", I present to you a work-around to both embrace the future, and live with the past. #40.

### CODE REVIEW

**Comment by autoSteve** [comment]
"Squash and merge" probably for this one, @BJReplay. I didn't make the commit name real handsome...

**Review by BJReplay — APPROVED** [review]
I am trusting your python skillz on this. Reviewing from phone.

OK if you are happy.

**Comment by autoSteve** [comment]
Oh, ye of much faith...

**Comment by autoSteve** [comment]
We really need another one Phythoned up to check me... Lols. Given the 4.0.29 debacle-ish.

**Comment by autoSteve** [comment]
We need a way to connect privately, @BJReplay, to discuss all things 429. You could subscribe to https://www.map59.com I guess, which woud reveal an email. If you want. Then un-sub. If you want.

**Comment by autoSteve** [comment]
At the very least it would give context to my profile picture...

**Comment by BJReplay** [comment]
> You could subscribe to https://www.map59.com I guess, which woud reveal an email. 

Done (or at least attempted - with an obvious email - but no confirmation received.

**Comment by BJReplay** [comment]
> We really need another one Phythoned up to check me... Lols. Given the 4.0.29 debacle-ish.

I once wrote a python thing by extensive copy-pasta work - and it works, but I really am a newb.  I understand what you mean when you say kwarg, but wouldn't know to look for that as an explanation for a problem.

**Comment by autoSteve** [comment]
Sorry, @BJReplay. kwarg = keyword argument.

If a function is declared with func(param1, param2, param3, **kwargs) then param1, param2, param3 are all required parameters, and any other parameters (like having the format ```, version=7```) can be looked up in a loop looking for the ```version``` name.

So earlier HA versions do not understand what ```version=``` means, and rather than simply ignore it (which you shouldn't do), HA sensibly bomb out.

Yeah, my subscriptions in Ghost must be busted. We'll work something out. (But now that you know my web site, guessing my email is a possibility. steve@.

This message will self destruct when you work it out...

**Pull request merged**
