### PR TITLE
Fifteen minute shift, because 30-minute averages

### PR DESCRIPTION
**Pull request by autoSteve**
I noticed today, because clear skies that every sensor in forecasts appears shifted by fifteen minutes. Plus @gcoan's example chart. This is the fix, pending further testing.

### CODE REVIEW

**Review by BJReplay — COMMENTED** [review]
OK, I'm gonna need an image to understand.

Maybe not an image, but an explanation....

Are you saying that each 30 minute forecast has to be shifted forward (e.g. to chart) by fifteen minutes?

I coulda sworn that the data returned by Solcast was the average insolation forecast by their engine for the period ending at the UTC time provided, so I'm guessing this is to improve the display.

**Comment by autoSteve** [comment]
Have a look at forcast "now", and compare to the chart. Almost bang on now vs. reality.

Currently real-world testing the "remaining" sensors using the latest commit (I got the shift wrong in code), and will have a result at 10:45 (which is a one hour interval from 09:45).

image

**Comment by BJReplay** [comment]
That makes more sense -  shift back 15 minutes (forecast timestamp is period ending from memory).

**Comment by autoSteve** [comment]
At 09:45:
7866kWh forecast next X hour (1hr)
10.3 actual solar generation

At 10:45, should expect 18.1kWh

Slightly off, but a moment before I took the snip it was showing 18.1.

image

Another test commencing 10:50.

**Comment by autoSteve** [comment]
At 10:50:
9,157Wh forecast next X hour (1hr)
18.9kWh actual solar generation
At 11:50, should expect 27.2kWh.
Actual generation for the hour: 27.9kWh

image

Next test that started at 11:05 was ruined by battery hitting 100% charge.

**Comment by BJReplay** [comment]
> Next test that started at 11:05 was ruined by battery hitting 100% charge.

LOL - I won't get there until mid-September at the earliest (but that's a 13-year-old 4.8kW system).  Today is the first transition day though where the charge algo has decided no charging required to get through peak, which is nice.

**Comment by autoSteve** [comment]
I haven't used any power from the grid for eight days, 3.55kWh off-peak nine days back, then the two prior were also zero. Basically I've been paying daily supply charge (or less, like today). Month-to-date bill estimate $12.50, which ain't bad for Winter.

I did go extreme with this current set up... 😉 One PW was not enough, two is too many because big suckers. I do wish there was a feature to limit charge to 80% to extend cell life, which I'd trigger if the solar forecast for tomorrow expected full fill.

**Comment by autoSteve** [comment]
I'm calling the full day test of actual vs. calculated forecast numbers a success, given the terrific clear skies today. Chart matched spline forecast numbers, and both sets of remaining and moment sensors well matched generation and expected.

There is still a tendancy for actual to lag the forecast a touch, but I'm pretty sure that's because I don't have my site azimuth 100% accurate at solcast.com.au.

image

**Comment by autoSteve** [comment]
(The chart lag of actual could also be down to slow sensor update from the Tesla gateway. Even five/ten minutes lag would do it, and this makes sense given the lag is quite consistent going up and coming down.)

**Comment by isorin** [comment]
A welcome change, Steve, I wanted to flag this for some time as well.
The averages we get for the 30 minutes intervals should be associated with the middle of the intervals. (not the start of the intervals).

**Comment by autoSteve** [comment]
Today was a carbon copy of yesterday, so I reckon this is good to go, @BJReplay.

**Comment by BJReplay** [comment]
I'm happy to merge, or happy to do a release as you prefer.  Release would also mean (possibly - who knows?) an update to readme as displayed in HACS at the downside of resetting my graph :)

**Comment by BJReplay** [comment]
I reckon release.  Make everyone have your goodness 🤣

**Pull request merged**
