### PR TITLE
Post v4.1.4, all readme so far

### PR DESCRIPTION
**Pull request by autoSteve**
Nit-picking the readme to be kind to readers and removing a known issue.

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
Snap. Just nit-picked some more. 😂

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
I take it that adding the blank lines somehow pleases HACS display?

**Comment by BJReplay** [comment]
> I take it that adding the blank lines somehow pleases HACS display?

I'm **_hoping_** that adding the blank lines somehow pleases the HACS display.

But it's chicken soup.

**Review by autoSteve — COMMENTED** [review]
Looks fine to me. Hope it works.

**Pull request merged**
