### PR TITLE
Update README.md

### LINKED ISSUE #129: Images are not rendering in the readme displayed in HACS
This is being investigated.

For the time being please utilise the readme at https://github.com/BJReplay/ha-solcast-solar if you want to see these.

### PR DESCRIPTION
**Pull request by autoSteve**
This should do it.

Will close #129.

I think it will be worthwhile doing an immediate v4.1.2 for this, but replicating the v4.1.1 release description, adding the image fix. Set full changelog to v4.1.0..v4.1.2.

### CODE REVIEW

**Comment by autoSteve** [comment]
Draft v4.1.2 is prepped and ready to go on your review.

**Comment by autoSteve** [comment]
Holy heck. Fifty have already downloaded v4.1.1.

**Review by BJReplay — APPROVED** [review]
Thanks!

**Comment by BJReplay** [comment]
Some of those images would **never** have shown up in HACS - I used the existing links as the template for the replacement of the pasted images.

**Comment by autoSteve** [comment]
So we're good to go? Looks fine to me...

**Comment by BJReplay** [comment]
Yep

**Pull request merged**
