### PR TITLE
Move pasted images to screenshots

### PR DESCRIPTION
**Pull request by BJReplay**
Moved all pasted screenshots to SCREENSHOTS

Changed width attributes on a few that I felt were too small.

Removed width attributes on a few others.

### CODE REVIEW

**Review by autoSteve — APPROVED** [review]
Looks good to me!

**Comment by BJReplay** [comment]
> Looks good to me!

@autoSteve, for the life of me I can't work out how HACS fetches the readme - it still has image links that point to the v3 branch.

I have deleted the custom repository, re-downloaded it, rereshed the iframe, and even uninstalled and reinstalled HACS and it is still serving up old links.

**Comment by autoSteve** [comment]
I know, right? It ain't in the .ZIP.

It must be a cached version of the readme as-at the release moment. But howwwww???

I even considered looking at the source code to find out then lost interest.

Maybe try slaughtering a chicken then re-create your API key. You didn't try those things...

**Comment by BJReplay** [comment]
> then re-create your API key

Actually, I did

No chickens were harmed.

We will see what happens when we next release.

**Pull request merged**
