### PR TITLE
Inconsequential things

### PR DESCRIPTION
**Pull request by autoSteve**
'Nuf said.

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]
nuff said

**Comment by autoSteve** [comment]
> actually, gee it's nice developing

Add GitHub co-pilot and the pair is quite amazing. That shit writes code that's actually pretty good.

**Comment by BJReplay** [comment]
> Add GitHub co-pilot

It keeps on nagging me to start a trial. I should give it a go when I have
- car
- ocpp charger
- time 😂

**Comment by autoSteve** [comment]
> - car
> - ocpp charger
> - time 😂

and

- ten bucks a month for stuff I swore I would never use...

And yet, I was fixing to craft a check for specifying multiple same API keys for the integration as yeah, nah. Copilot got some intent wrong, but fuck me it automagically added `return self.async_abort(reason="API key duplicated")`. And that's quite clever to suss out what I was doing, saving me from typing it, even if I changed the message...

But ten bucks a month to save my fingers some work? Umm... Whatever. I did it anyway. It's done way cleverer shit that has dropped my jaw, so I'm grudgingly in.

**Comment by BJReplay** [comment]
> * ten bucks a month for stuff I swore I would never use...

Yeah, I'll give it a go.

I was comically disappointed when I was first trying to figure out python (see https://github.com/jasonacox/Powerwall-Dashboard/tree/main/weather/contrib and https://github.com/jasonacox/Powerwall-Dashboard/tree/main/tools/ecowitt-weather-history for my hilarious early efforts) when ChatGPT would come up with absolutely completely wrong suggestions for how to parse json using python.

It would come up with stuff that looked good but was just wrong.  And, at that stage, I had no idea on how to set up any sort of dev or debug client, so was flying blind.

Since then, I've had the chance to review some T-SQL produced by co-pilot (probably six months ago), and it runs, but it is still comically inefficient.  Now, in this case, I'm perhaps judging too harshly, as I think in sets and can run optimisers in my heads and construct complex queries so that optimisers make the right decisions without thinking, and there's still a lot of art to that, because you still need to understand cardinality, keys, selectivity, and stuff like that, and language models can't do that.

That's my beef with AI writing code: syntactically it can be right, but it can't always write performant code, and that matters, still.  It matters for UX, it matters for the web, it matters for phones, and it matters for cars, and it matters for banking, and airlines, and medical and industrial, and pretty much everything except startups trying to get their round A away.

But nah, yeah, I'll give it a go.  I might learn something 🤣

**Pull request merged**
