### PR TITLE
V4.1.1 release prep

### PR DESCRIPTION
**Pull request by autoSteve**

### CODE REVIEW

**Comment by autoSteve** [comment]
Release drafted.

**Review by BJReplay — APPROVED** [review]

**Comment by BJReplay** [comment]
There's quite a distinct pattern of downloads where it tails off during the day here - overnight in Europe - and speeds up around 7:30am BST
image

**Comment by autoSteve** [comment]
Very interesting. I think we have loads of Euro users.

I still can't make announcements 'announcements', despite code owner status. Guess you are the only one who can.

**Comment by BJReplay** [comment]
Yes re Announcements - as far as I can tell, (though I haven't run it to ground), for a non-organisation repo, only one owner.

LOL.

image

**Comment by BJReplay** [comment]
Have you seen the readme in HACS after installing and restarting @autoSteve? 

FML

**Comment by autoSteve** [comment]
What the actual??? The image changes looked perfect!

I wonder if there is something special required for HACS. 🤷‍♂️

**Comment by autoSteve** [comment]
_All_ if the images are gone, even the ones we did not touch...

**Comment by BJReplay** [comment]
It's bizarre, because some of the images that were already hosted in .github/SCREENSHOTS are also gone.  Even the ones where I didn't touch the width attributes.

It's as if HACS does a prospective fetch of images, tries to work out if they exist, and decides if they don't, to remove a link from the readme.  I'm assuming it manipulates the readme and stashes a version, and that's a once off process for a new release, and it serves that version forever more.

**Comment by autoSteve** [comment]
Open a HACS issue? I see nothing in the Googlebox...

**Comment by BJReplay** [comment]
Yeah, I'm just reading through HACS closed issues, and the closest I can find is https://github.com/hacs/integration/issues/3362, but I'll do a little more looking.

**Comment by autoSteve** [comment]
The closest I can get from Ludeeus.

We use relative URLs...

> The author needs to switch from relative to static URLs for them to ensure that the content properly works outside of github.com.
> Nothing I can do about it.

**Comment by autoSteve** [comment]
https://github.com/hacs/integration/issues/2850

**Comment by autoSteve** [comment]
Confirmed with an autoSteve release. I'll create a PR.

**Comment by BJReplay** [comment]
I can see you've created a branch already.  Too fast for me.

I was busy taking phone calls - in IBM parlance, the air movement device is unserviceable due to faecal contamination as my report starts doing the rounds.

**Comment by autoSteve** [comment]
The designation v4.1.2 sounds way nicer than v4.1.1 anyway, getting us even further away from a dot-zero release.

I worked at NetApp for many years, and every odd-numbered ONTAP release was always one to be wary of, so that superstition might be spooking me...

Glad we got it sorted.

We're allowed the odd SNAFU I reckon. Training wheels still on and all that...

**Comment by autoSteve** [comment]
OMG.

The pull request to change the images to light mode is actually reflecting in the current release HACS version of the readme.

So it's just the readme _markdown_ that gets cached, and not images... (kind of makes sense.)

#learning...

**Comment by BJReplay** [comment]
image

**Pull request merged**
