### PR TITLE
Post v4.1.6

### PR DESCRIPTION
**Pull request by autoSteve**
Site breakdown attributes are broken

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
Latest re. #166. Adds warnings if sites data is dodgy.

**Comment by autoSteve** [comment]
Latest re. #166. Fixes buggered up forecast list slice for sites added some time after install.

**Comment by autoSteve** [comment]
Fixes field confirmed by @bajarrr.

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
Discussion point, @BJReplay.

I had added `state_class` to many sensors, but on re-reading the documentation the impact of this is to opt-in those sensors to LTS storage. I do not think that is a good thing to do, so these have been rolled back to `None`.

Geoff wants consistency of the `state_class` for day 2/3/4/5/6/7 sensors. This change would also opt-in those sensors for LTS, which I am not convinced is the right change to make.

https://developers.home-assistant.io/docs/core/entity/sensor/

It does bring consistency, but at what cost? LTS is not of any use for these sensors, and it could be argued that the correct consistent approach would be to _remove_ the state class of the day 1 sensor.

Thoughts and opinion?

**Comment by BJReplay** [comment]
I see no value in LTS for forecasts. The only thing that there is any value for LTS is observations. Possible exception for latest forecast, but, FFS, if you want to do statistical analysis on Solcast forecasts, choosing the HA database as your storage solution is the wrong answer.

**Comment by autoSteve** [comment]
I'm happy with this now. Sending it.

**Pull request merged**
