### PR TITLE
Simplify configure

### PR DESCRIPTION
**Pull request by autoSteve**
What an adventure. Thanks HA core crew.

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Comment by BJReplay** [comment]
I've tested all configuration options except changing my API key and putting in different API keys or adding / removing more than one key / quota.

I haven't exercised code changes around adding / removing arrays since nothing has changed there.

**Comment by BJReplay** [comment]
I have updated forecasts with attributes turned on and off, and confirmed that they do populate (or not, as the case may be).

**Comment by autoSteve** [comment]
Squeezed in a picture update in readme.

**Comment by autoSteve** [comment]
It is free. I'd appreciate an announcement conversion please, @BJReplay.

**Comment by BJReplay** [comment]
> It is free. I'd appreciate an announcement conversion please, @BJReplay.

Done.  I got a bit distracted updating release.yml because it was using outdated workflows (that depend on node16).  Smashed the changes straight into main, because it won't break anything except our next release (if anything).

**Pull request merged**
