### PR TITLE
Post v4.0.38

### PR DESCRIPTION
**Pull request by autoSteve**
Konnichiwa @BJReplay san. One big sleep to go!

As the readme would say in future:

* Updates to sensor descriptions, and alter some sensor names by @isorin (Potentially breaking for UI/automations/etc. should these these sensors be in use. Power in 30/60 minutes, and custom X hours sensor.) **(already merged)**
* Remove dependency on scipy library by @autoSteve **(good riddance)**
* Add granular configuration options for attributes by @autosteve **(nerd knobs to achieve less clutter)**

The release discussion would gush on and on about how good folks are to dive into an alpha.

The readme and manifest are good to go in this PR.

I will have the trusty M2 Max with me, but will obviously be rubbernecking most of the time.

### CODE REVIEW

**Comment by autoSteve** [comment]
Ref. #84, #85, #87.

**Review by BJReplay — APPROVED** [review]
Huge change. I'm gonna load it from in flight wifi for shits and giggles.

I am also gonna put up an announcement that we're both out of the country (which, in reality, means you're out of the country) so please be patient with bug reports, read the readme carefully, and stick with either the release version or the pre dodgy include version.

**Comment by autoSteve** [comment]
🤣🤣🤣

I'ma gonna release this as v4.0.39, then back away slowly to Tokyo... Soz...

**Comment by autoSteve** [comment]
Ramen for breakfast, assuming, of course, that QF have avoided the worst of the CloudStrike BSOD sh*t-show. Seems like they have. Being QFF Plat I should be able to jump most queues.

It re-justifies my unwavering position (after an event many years ago) that JetStar will _never_ receive ONE DOLLAR of revenue from me again. And they're grounded until the morning (idiots), and will have quite the backlog of angry customers wanting to squeeze onto flights. (How's ya revenue after paying CloudStrike, folks?)

I just grab the popcorn and chuckle...

I will not release v4.0.39 on a Friday. I am reminded that read-only Friday is sacred for sysadmins... Saturday??? Hmmm... Home Assistant folks are awake and willing on a weekend, and they can easily revert to a prior version.

But .39 is a rock from what I can tell so far.

I shall decide in the morning. Thanks for the review.

**Pull request merged**
