### PR TITLE
V4.1.5 prep

### PR DESCRIPTION
**Pull request by autoSteve**
Should have squeezed this into the merge just done.

### CODE REVIEW

**Review by BJReplay — APPROVED** [review]

**Comment by autoSteve** [comment]
And it is set free.

I'd appreciate annoucement-ising of the discussion.

**Comment by autoSteve** [comment]
v4.1.3 discussion too, while you're down there.

**Comment by BJReplay** [comment]
Readme block quotes mostly (but not completely) render better. The important is completely missing, but others I think are all there.

Extra breaks FTW

**Comment by autoSteve** [comment]
Brilliant work-around by gaining an understanding the underlying issue!

**Pull request merged**
