### PR TITLE
Updates to sensor description

### PR DESCRIPTION
**Pull request by isorin**
Updated description for some sensors.
Renamed "forecast_custom_hour" to "forecast_custom_hours" to better reflect its meaning.

### CODE REVIEW

**Comment by autoSteve** [comment]
Nice @isorin.

I take it that it won't fix this crap happening for the custom sensor?

image

How _does_ one fix that happening for the custom sensor?

**Comment by isorin** [comment]
> Nice @isorin.
> 
> I take it that it won't fix this crap happening for the custom sensor?
> 
> image
> How _does_ one fix that happening for the custom sensor?

I will look into it.

**Comment by autoSteve** [comment]
Good luck. I can't even find how the code does that friendly name! Let alone the whole "next_1_hours" thing, which would be based on the initial setting.

**Comment by isorin** [comment]
> Good luck. I can't even find how the code does that friendly name! Let alone the whole "next_1_hours" thing, which would be based on the initial setting.

I manually updated the config in HA to "2" hours and the name updated for me.
image

I don't know how it does it either and there is no way to change it through the UI after the installation, isn't it?

**Comment by autoSteve** [comment]
It changes the 'friendly' name somehow (like you I can't see how), but not the underlying sensor.blahblahblah name, which always seems to carry _1_hour since it gets created. And I can't even see how _either_ name is produced. What magic is this? I'm scared and confused...

**Review by autoSteve — APPROVED** [review]

**Comment by autoSteve** [comment]
Oooo...

Found this nugget in strings.json:

`"forecast_custom_hour": {"name": "Forecast Next {forecast_custom_hour} Hours"},`

There's your friendly name, right there.

**Comment by isorin** [comment]
Yes, I know about this:
"forecast_custom_hour": {"name": "Forecast Next {forecast_custom_hour} Hours"},

We need someone to test a fresh install.
I don't know if it's set properly or it is always set to "Forecast Next 1 Hours" regardless of what the user chooses.
Also, it would be nice to expose that setting as we have "Use forecast field".

If it's always set to "Forecast Next 1 Hours" then we could just use ""Forecast Next X Hours".

**Comment by autoSteve** [comment]
Righto. I think this is all about trying to be "friendly" and translating sensor names into different languages, including English.

If the translation did not include a modification based on setting then the sensor name would remain as 'forecast_custom_hours', or _X_ hours, or whatever.

I blame Oziee and his forked predecessors for shooting us in the foot today, by trying to keep the friendly name updated. I think it is what it is, and that HA will hold on to the sensor name given to it originally. I've seen that before, with some of the C-Bus coding I've done to integrate.

Without force removing the sensor and re-adding it I can see no alternative but to live with it. Even if it makes my eye twitch.

Setting up from scratch would just result in the same "Forecast Next 1 Hours" because of the default config.

I vote to change the translations/strings. It isn't going to update the sensor name for existing installs without an unnatural act. Or do folks like that it updates the friendly name, and results in a weird one hour sensor name? Who knows? Ugh!

Oziee!!!!

**Comment by autoSteve** [comment]
(An out-there thought without actually trying to to see if it is possible... kill the existing 1 Hours sensor if it exists, create a new "generic" one, and _then_ set the friendly name... The sensor name would not change because it was already set...)

**Comment by isorin** [comment]
I'm also in favour of changing:
"forecast_custom_hours": {"name": "Forecast Next {forecast_custom_hours} Hours"},
to
"forecast_custom_hours": {"name": "Forecast Next X Hours"},

**Comment by autoSteve** [comment]
I kind-of agree. That would not change the sensor name for existing installs. Because HA.

I'm going to naval gaze about this tomorrow. It has to be possible to kill off the existing sensor and replace it with a fresh one, and _then_ update its friendly name to what ever we want. That scenario doesn't break future automations, etc.

But, how many people rely on this dodgy sensor name as _1_hour for automations, etc.? I'm tipping not many... If any. I wouldn't.

I'd love to know the history of it. _Someone_ must use it, or it wouldn't be there, especially given Oziee's zero-tolerance attitude to chaff, and surely they would have at first been grateful, then called out its shortcomings... Which maybe Oziee dismissed? 🤷‍♂️🤦🏻 Who knows? Guessing.

**Comment by isorin** [comment]
Btw. this code here is the one that does the placeholder substitution:
`        #doesnt work :()
        if entity_description.key == "forecast_custom_hours":
            self._attr_translation_placeholders = {"forecast_custom_hours": f"{coordinator.solcast._customhoursensor}"}
`

I will push the changes to rename it.

**Comment by autoSteve** [comment]
> `#doesnt work :()`

Lols.

**Review by autoSteve — COMMENTED** [review]
I doubt it changes anything for existing users, and also won't update the friendly name on config change as is, which some may be relying on. This is a tricky one.

**Comment by isorin** [comment]
It did for me, I updated the code and restarted HA and now I see:
"Forecast Next X Hours"
where before I had:
"Forecast Next 2 Hours"

It doesn't update the entity_id but if you didn't change the name, it updates it.

**Comment by autoSteve** [comment]
That is gold.

**Review by autoSteve — APPROVED** [review]

**Comment by autoSteve** [comment]
Is that for the friendly name or the sensor name? Whjat do you see in the developer tools against that sensor? I've never got it to change from default at creation...

**Comment by autoSteve** [comment]
I do still wish the 'friendly' name updated, but we can't have everything...

**Comment by autoSteve** [comment]
I've not found a way to separately set the friendly name, so folks can customise that themselves if desired.

**Pull request merged**
